### ISSUE TITLE
What's the difference between FCViT TokenMixer and GCBlock from GCNet?

### ISSUE THREAD

**Issue by ZRandomize** [ma-xu/FCViT#1]
Hi, I read the paper and found the global average pooling and info bottleneck looks similar to GCBlock, what is there diiference?

**Comment by ma-xu** [comment]
@ZRandomize Thanks for the questions. 

I do think the tokenmixer in our paper and gcblock are quite different. There is no gap in GCNet and bottleneck structure is a common design for parameter efficiency (besides, we also introduced the competitive info.  bottleneck).

We appreciate the question to further improve our work and would add the abaltion study (using gcblock as a token-mixer) in our revision.

**Comment by ZRandomize** [comment]
Thx!
