### ISSUE TITLE
Training log

### ISSUE THREAD

**Issue by LMMMEng** [ma-xu/FCViT#3]
Thank you for your excellent work.

Could you please provide the training log (ImageNet) for reference?

**Comment by ma-xu** [comment]
Thanks for your interest. summary.csv is in the download link. For training logs like training time, we may provide latter if necessary.

**Comment by LMMMEng** [comment]
Many thanks!

**Comment by LMMMEng** [comment]
The training log of FCViT-B24 is incomplete, could you please release the completed one? (epoch0--309),  moreover, I did not find the log of B36. Could you please provide it?

**Comment by ma-xu** [comment]
It is resumed, hence I uploaded the last one.  I will double-check the logs in the server and upload them.

**Comment by LMMMEng** [comment]
Thank you!

I have another query. I noticed that fcvit used BN in patch embedding layers, but SyncBN is not activated during training, did SyncBN matter in the training of fcvit?

**Comment by ma-xu** [comment]
@LMMMEng It may have negligible influence, which can be ignored.
