### ISSUE TITLE
Detection model results

### ISSUE THREAD

**Issue by C-C-Y** [ma-xu/FCViT#5]
Hello, I want to get the model results FCViT-B24 for detection, this one is on google cloud drive, but I don't have access, thank you.

**Comment by ma-xu** [comment]
Just tested, it is publicly accessible.

**Comment by C-C-Y** [comment]
> Just tested, it is publicly accessible.

Sorry, I don't know what the problem is, the FCViT-B12 results for detection I have access to, but when I access FCViT-B24 Google Drive shows that I don't have permission.

**Comment by ma-xu** [comment]
@C-C-Y Thanks for the issue. Updated. Please double-check again.
